import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import {
  extractVideoId,
  transcribeVideo,
  listAvailableLanguages,
  type TranscriptSegment,
} from "../lib/youtube.ts";
import {
  ScribeError,
  VideoNotFoundError,
  CaptionsDisabledError,
  LanguageNotAvailableError,
} from "../lib/errors.ts";

const TranscribeParamsSchema = {
  url: z
    .string()
    .describe("YouTube video URL or video ID (e.g. https://youtu.be/dQw4w9WgXcQ or dQw4w9WgXcQ)"),
  language: z
    .string()
    .optional()
    .default("en")
    .describe("Preferred caption language code (e.g. 'en', 'es', 'fr'). Defaults to 'en'."),
  timestamps: z
    .boolean()
    .optional()
    .default(false)
    .describe("Include timestamps in the output. Only applies to 'text' format."),
  format: z
    .enum(["text", "srt", "json"])
    .optional()
    .default("text")
    .describe(
      "Output format: 'text' (clean prose), 'srt' (SubRip subtitles), or 'json' (structured array with timing data). Defaults to 'text'."
    ),
};

function buildErrorMessage(err: unknown): string {
  if (err instanceof VideoNotFoundError) {
    return `Video not found or unavailable. Make sure the video is public and the URL/ID is correct.\n\nDetails: ${err.message}`;
  }
  if (err instanceof CaptionsDisabledError) {
    return `This video does not have captions available. The creator may have disabled them, or the video may be too new for auto-generated captions.\n\nDetails: ${err.message}`;
  }
  if (err instanceof LanguageNotAvailableError) {
    return `${err.message}\n\nTip: Use a supported language code or omit the language parameter to use the first available language.`;
  }
  if (err instanceof ScribeError) {
    return `Transcription failed: ${err.message}`;
  }
  if (err instanceof Error) {
    return `Unexpected error: ${err.message}`;
  }
  return "An unknown error occurred during transcription.";
}

function formatJsonResult(segments: TranscriptSegment[]): string {
  return JSON.stringify(segments, null, 2);
}

export function registerYoutubeTranscribeTool(server: McpServer): void {
  server.tool(
    "youtube_transcribe",
    "Transcribe a YouTube video by extracting its captions/subtitles. Returns the transcript in the requested format (text, SRT, or JSON). Requires the video to have captions enabled (manual or auto-generated).",
    TranscribeParamsSchema,
    async (params) => {
      const { url, language, timestamps, format } = params;

      console.error(`[scribe] youtube_transcribe called: url=${url} lang=${language} format=${format} timestamps=${timestamps}`);

      // Validate the URL/ID first and give a helpful early error
      const videoId = extractVideoId(url);
      if (!videoId) {
        return {
          isError: true,
          content: [
            {
              type: "text" as const,
              text: `Invalid YouTube URL or video ID: "${url}"\n\nSupported formats:\n- https://www.youtube.com/watch?v=VIDEO_ID\n- https://youtu.be/VIDEO_ID\n- https://youtube.com/shorts/VIDEO_ID\n- VIDEO_ID (bare 11-character ID)`,
            },
          ],
        };
      }

      try {
        // When timestamps requested with text format, fetch as JSON to get timing data
        const fetchFormat = format === "text" && timestamps ? "json" : format;
        const result = await transcribeVideo(url, { language, format: fetchFormat });

        // Build metadata header
        const autoLabel = result.isAutoGenerated
          ? " (auto-generated)"
          : " (manual)";
        const header = [
          `Video ID: ${result.videoId}`,
          `Language: ${result.language}${autoLabel}`,
          `Format: ${format}`,
          "",
        ].join("\n");

        let body: string;
        if (format === "json") {
          body = formatJsonResult(result.transcript as TranscriptSegment[]);
        } else if (format === "text" && timestamps) {
          const segments = result.transcript as TranscriptSegment[];
          body = segments
            .map((s) => {
              const totalSec = Math.floor(s.startMs / 1000);
              const m = Math.floor(totalSec / 60);
              const sec = totalSec % 60;
              const ts = `[${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}]`;
              return `${ts} ${s.text}`;
            })
            .join("\n");
        } else {
          body = result.transcript as string;
        }

        return {
          content: [
            {
              type: "text" as const,
              text: header + body,
            },
          ],
        };
      } catch (err) {
        console.error(`[scribe] Error transcribing ${videoId}:`, err);
        return {
          isError: true,
          content: [
            {
              type: "text" as const,
              text: buildErrorMessage(err),
            },
          ],
        };
      }
    }
  );

  server.tool(
    "youtube_list_languages",
    "List all available caption languages for a YouTube video. Useful for discovering which languages are available before transcribing.",
    {
      url: z
        .string()
        .describe("YouTube video URL or video ID"),
    },
    async (params) => {
      const { url } = params;

      const videoId = extractVideoId(url);
      if (!videoId) {
        return {
          isError: true,
          content: [
            {
              type: "text" as const,
              text: `Invalid YouTube URL or video ID: "${url}"`,
            },
          ],
        };
      }

      try {
        const languages = await listAvailableLanguages(videoId);

        if (languages.length === 0) {
          return {
            content: [
              {
                type: "text" as const,
                text: `No captions available for video: ${videoId}`,
              },
            ],
          };
        }

        const lines = languages.map(
          (l) =>
            `- ${l.code}: ${l.name}${l.isAutoGenerated ? " (auto-generated)" : " (manual)"}`
        );

        return {
          content: [
            {
              type: "text" as const,
              text: `Available languages for ${videoId}:\n\n${lines.join("\n")}`,
            },
          ],
        };
      } catch (err) {
        console.error(`[scribe] Error listing languages for ${videoId}:`, err);
        return {
          isError: true,
          content: [
            {
              type: "text" as const,
              text: buildErrorMessage(err),
            },
          ],
        };
      }
    }
  );
}
